export { default as DetailAppointment } from "./pages/appointment/DetailAppointment"
export { default as HistoryAppoinment } from "./pages/appointment/HistoryAppoinment"
export { default as ListClinic } from "./pages/clinic/ListClinic"
export { default as ListDoctor } from "./pages/doctor/ListDoctor"
export { default as Profile } from "./pages/Profile"
export { default as Stadistics } from "./pages/Stadistics"
