export { default as ListClinic } from "./pages/clinic/ListClinic"
export { default as HistoryAppoinment } from "./pages/HistoryAppoinment"
export { default as Profile } from "./pages/Profile"
export { default as ListSpecialty } from "./pages/speciality/ListSpecialty"
export { default as Stadistics } from "./pages/Stadistics"
export { default as ListStudy } from "./pages/study/ListStudy"
