export { default as ForgotPassword } from "./pages/ForgotPassword"
export { default as Login } from "./pages/Login"
export { default as NotFound } from "./pages/NotFound"
export { default as Register } from "./pages/Register"
export { default as ResetPassword } from "./pages/ResetPassword"
